### ISSUE TITLE
Util.java throws InvalidPathException on Windows

### ISSUE THREAD

**Issue by paulk-asert** [apache/incubator-datasketches-java#296]
The test suite fails with numerous errors on Windows:
```
[ERROR] Failures:
[ERROR]   UtilTest.resourceBytesCorrect:348 » InvalidPath Illegal char <:> at index 2: /...
[ERROR]   KllFloatsSketchTest.deserializeOneItemV1:355 » InvalidPath Illegal char <:> at...
[ERROR]   ForwardCompatibilityTest.check030_1000:49->getAndCheck:121 » InvalidPath Illeg...
[ERROR]   ForwardCompatibilityTest.check030_50:39->getAndCheck:121 » InvalidPath Illegal...
[ERROR]   ForwardCompatibilityTest.check060_1000:69->getAndCheck:121 » InvalidPath Illeg...
[ERROR]   ForwardCompatibilityTest.check060_50:59->getAndCheck:121 » InvalidPath Illegal...
[ERROR]   ForwardCompatibilityTest.check080_1000:89->getAndCheck:121 » InvalidPath Illeg...
[ERROR]   ForwardCompatibilityTest.check080_50:79->getAndCheck:121 » InvalidPath Illegal...
[ERROR]   ForwardCompatibilityTest.check083_1000:109->getAndCheck:121 » InvalidPath Ille...
[ERROR]   ForwardCompatibilityTest.check083_50:99->getAndCheck:121 » InvalidPath Illegal...
[ERROR]   ArrayOfDoublesUnionTest.noSupportHeapifyV0_9_1 » Test
Expected exception of t...
[ERROR]   ArrayOfDoublesUnionTest.noSupportWrapV0_9_1 » Test
Expected exception of type...
[ERROR]   CompactSketchWithDoubleSummaryTest.serialVersion1Compatibility:192 » InvalidPath
[INFO]
[ERROR] Tests run: 1387, Failures: 13, Errors: 0, Skipped: 0
```
The stacktrace of one of the errors is shown below:
```
[ERROR] serialVersion1Compatibility(org.apache.datasketches.tuple.CompactSketchWithDoubleSummaryTest)  Time elapsed: 0.002 s  <<< FAILURE!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/projects/incubator-datasketches-java/target/test-classes/CompactSketchWithDoubleSummary4K_serialVersion1.bin
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.apache.datasketches.Util.getResourceBytes(Util.java:761)
        at org.apache.datasketches.tuple.CompactSketchWithDoubleSummaryTest.serialVersion1Compatibility(CompactSketchWithDoubleSummaryTest.java:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by leerho** [comment]
Thank you so much for finding and solving this!

Lee.
